### PR TITLE
Add new post about building Ruby on Rails images with Buildah

### PR DESCRIPTION
**Pull request by Fodoj**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@Fodoj  thanks so much for putting this together.  What you have here looks good, but you need to add one more file.  Can you create a  _posts/2019-06-08-ruby.md file and fill it's contents with the contents from:
https://github.com/containers/buildah.io/blob/master/_posts/2019-04-16-cinc.md
Then change out the author and such and change the description.  You probably can just cut/paste the description from your new post.

The "new" file that you've included will show a link on the home page, but it might cycle out over time.  By adding the second file, the link will also be added to the "blogs" page which you get to by clicking on the blogs link on the main page.  Those posts won't be wiped over time, but will be retained.

Thanks again!

**Comment by Fodoj** [comment]
@TomSweeneyRedHat done! thanks

**Comment by TomSweeneyRedHat** [comment]
LGTM, thanks @Fodoj !

**Pull request merged**
