### PR TITLE
Buildah v1.7 Release Announcement

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Add blogs for v1.7 Release Announcement.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg, please give a head nod on the push in parallel change.  If that's right, then we can merge this.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL and LGTM/merge this if appropriate.  In email received verification from @vrothberg on the push also being in parallel.

**Comment by vrothberg** [comment]
LGTM, I really like the summary!

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat We need a link under `What's New` also.

**Pull request merged**
